services:
  qdroid-server:
    restart: unless-stopped
    container_name: qdroid-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_DIALECT
      - DB_HOST=mariadb
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - LOG_LEVEL
      - JWT_SECRET
      - RABBITMQ_API_URL=http://rabbitmq:15672
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
      - ARGON2_TIME
      - ARGON2_MEMORY
      - ARGON2_THREADS
      - ARGON2_KEYLEN
      - ARGON2_SALTLEN
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - qdroid-network

  rabbitmq:
    restart: unless-stopped
    container_name: rabbitmq
    hostname: queuedroid.com
    image: rabbitmq:4-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - qdroid-network

  mariadb:
    restart: unless-stopped
    container_name: mariadb
    image: mariadb:11.4
    volumes:
      - mariadb-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - qdroid-network

volumes:
  mariadb-data:
  rabbitmq-data:

networks:
  qdroid-network:
