definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  handlers.SignupRequest:
    properties:
      email:
        description: |-
          User's email address
          required: true
        example: user@example.com
        type: string
      password:
        description: |-
          User's password
          required: true
        example: MySecretPassword@123
        type: string
      phone_number:
        description: Optional phone number
        example: "+2371234567890"
        type: string
    type: object
  handlers.SignupResponse:
    properties:
      message:
        description: Signup successful message
        example: Signup successful
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/auth/signup:
    post:
      consumes:
      - application/json
      description: Creates a new user account.
      parameters:
      - description: Signup request payload
        in: body
        name: signupRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.SignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Signup successful
          schema:
            $ref: '#/definitions/handlers.SignupResponse'
        "400":
          description: Bad request, missing required fields
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "409":
          description: Duplicate user
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
