name: Production Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Execute Deployment Script on Server
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://api.queuedroid.com
    steps:
      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e

            echo "============================"
            echo "🚀 Updating repository ..."
            echo "============================"
            cd ${{ secrets.PROJECT_PATH }}
            if ! git pull; then
              echo "❌ Error updating repository!"
              exit 1
            fi
            echo "==============================="
            echo "✅ Repository update complete"
            echo "==============================="

            echo "========================="
            echo "🚀 Building project ..."
            echo "========================="
            if ! ${{ secrets.BUILD_CMD }}; then
              echo "❌ Error building project!"
              exit 1
            fi
            echo "==========================="
            echo "✅ Project build complete"
            echo "==========================="

            echo "============================="
            echo "Cleaning up production builds ..."
            echo "============================="
            if ! ${{ secrets.CLEANUP_CMD }}; then
              echo "❌ Error cleaning up builds!"
              exit 1
            fi
            echo "============================="
            echo "✅ Cleanup complete"
            echo "============================="
